<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['events_app_description'] = 'Приложение "Система событий" предоставляет возможность другим приложениям слушать события, которые происходят в системе';
$lang['events_app_name'] = 'Система событий';
