<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['events_app_description'] = 'The Event System app provides a way for other apps to listen for events that occur on the system';
$lang['events_app_name'] = 'Event System';
